---
abstract: 'Interact with the Buxfer webservice'
author:
  - 'Nathaniel Heinrichs <nheinric@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Buxfer
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  HTTP::Request::Common: 0
  JSON::XS: 0
  LWP: 0
  Moose: 0
  URI: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
